language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yqq g++-4.8
  - export CXX="g++-4.8"

before_script:
  - composer install --prefer-source --no-interaction --dev
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: c8a07ee2759b229cb3bee66fb112ef1ce95494c
